import Head from "next/head";

export default function Home() {
  return (
    <div className="bg-blackSecondary relative -mt-24 pt-24 ">
      <div className="elementor"></div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-colorText relative z-50">Hello Body</h1>
    </div>
  );
}
